services:
  app:
    build:
      context: ./docker/app
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./web_app:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db
    command: >
      sh -c "chown -R www-data:www-data /var/www && chmod -R 775 /var/www/storage /var/www/bootstrap/cache && php-fpm"

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  web:
    image: nginx:latest
    container_name: laravel_web
    ports:
      - "8080:80"
    volumes:
      - ./web_app:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:

